version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mdmgg

permissions:
  - object: /home/ec2-user/mdmgg/scripts
    pattern: "**"
    mode: '755'
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/run_new_was.sh
      timeout: 60
      runas: ec2-user